# Test build job

name: BUILD

# Triggers the workflow on push or pull request events
on: [ workflow_dispatch, pull_request ]
jobs:
  build-buildroot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: buildroot-rk3588
          
      - name: Install depends
        run: sudo apt-get install -y debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git
              
      - name: Submodules init
        working-directory: ./buildroot-rk3588
        run: |
          git submodule init
          git submodule update --recursive
           
      - name: Configure Buildroot
        working-directory: ./buildroot
        run: make BR2_EXTERNAL=../external rock5b_defconfig
      
      - name: Build Buildroot
        working-directory: ./buildroot
        run: make -j32
      
      - name: Run legal-info
        working-directory: ./buildroot
        run: make legal-info
        
      - name: Create SDK 
        working-directory: ./buildroot
        run: make sdk
        
      - name: Copy artifacts
        working-directory: ./buildroot
        run: | 
          mkdir ~/artifacts
          cp -v output/images/sdcard.img ~/artifacts
          mkdir ~/sdk
          cp -v output/images/*sdk*.tar.gz ~/sdk
      
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: download-artifacts
          path: ~/artifacts
          
      - name: Upload SDK GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: download-sdk
          path: ~/sdk
